services:
  db:
    container_name: pg_test
    image: postgres:17-bookworm
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Root!23456
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
