services:
  db:
    container_name: postgresql-database
    image: postgres:17-bookworm
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres!23456
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
